# Summary: configuration file for .github/workflows/yaml-linter.yml.

rules:
  colons:
    max-spaces-after: -1
  quoted-strings:
    required: only-when-needed
  document-start:
      present: false
  document-end:
      present: false
