name: Request an addition to the list
description: Suggest an item to be added to this awesome list
title: "[ADD] "
labels: [addition]
body:
  - type: markdown
    attributes:
      value: |
        _Note: if you want to make more than one addition, **please request each one as a separate issue**. This makes it easier to track and respond to requests._

  - type: textarea
    attributes:
      label: What is the URL for the item?
      placeholder: |
        https://github.com/ai4lam/awesome-ai4lam
    validations:
      required: true

  - type: textarea
    attributes:
      label: How should the item be described?
      description: The item will be linked, and a description will be added next to it. Please write a suitable description to be used for that purpose. Note that conciseness is important! Please take a look at the existing awesome-ai4lam list to get an idea of what is intended here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What section does it belong in?
      description: Please pick an existing section or subsection, or propose a new section title.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Final checklist
      options:
        - label: I have verified that the item does not already exist in the list
    validations:
      required: true
