name: Suggest an addition to the list
description: Suggest an item to be added to this awesome list
title: "[ADD] "
labels: [addition]
body:
  - type: markdown
    attributes:
      value: |
        _Note: if you want to suggest more than one addition, **please request each one separately**._

  - type: input
    attributes:
      label: What is the URL for the item?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is a suitable title and brief description?
      description: Please suggest a title for the link, and optionally, a **concise** description to be put next to it. (See the existing list for examples.)
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: What section does it belong in?
      options:
        - Learning Resources
        - Tools and Frameworks
        - Datasets
        - Projects, Initiatives, and Case Studies
        - Policies and recommendations
        - Conferences and Workshops
        - Journals and Magazines
        - —Other— (see next question)
    validations:
      required: true

  - type: textarea
    attributes:
      label: If you selected "other", what new section do you propose?
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Final checklist
      options:
        - label: I have searched the existing list to verify that this item is not in it.
    validations:
      required: true
